name: Maven Build

on:
  push:
    paths: 
      - '.mvn/wrapper/**'
      - 'pom.xml'
      - 'src/**'    
  pull_request:
    paths: 
      - '.mvn/wrapper/**'
      - 'pom.xml'
      - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Amend permission for Maven wrapper
      run: chmod +x mvnw
    - name: Build with Maven
      run: ./mvnw clean package
